CREATE TABLE TB_PARAMETRO (
  ID_PARAMETRO INTEGER PRIMARY KEY NOT NULL,
  NM_SISTEMA TEXT NOT NULL,
  NR_VERSAO_SISTEMA TEXT NOT NULL,
  NR_VERSAO_BANCO INTEGER NOT NULL,
  NM_COR_FOCO TEXT NOT NULL, 
  NM_COR_PADRAO TEXT NOT NULL, 
  FL_TELA_CHEIA TEXT DEFAULT 'S' NOT NULL,
  DT_INCLUSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DT_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TRIGGER tr_parametro_0 AFTER UPDATE ON TB_PARAMETRO 
BEGIN                                                                
  UPDATE tb_parametro SET dt_alteracao = current_timestamp WHERE id_parametro = old.id_parametro;                                     
END;

CREATE TABLE TB_TOMADA (
  ID_TOMADA INTEGER PRIMARY KEY NOT NULL, 
  NM_TOMADA TEXT NOT NULL, 
  FL_ATIVO TEXT DEFAULT 'S' NOT NULL,
  DT_INCLUSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DT_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TRIGGER tr_tomada_1 AFTER UPDATE ON TB_TOMADA
BEGIN                                                                
  UPDATE tb_tomada SET dt_alteracao = current_timestamp WHERE id_tomada = old.id_tomada;                                     
END;

CREATE TABLE TB_CATEGORIA (
  ID_CATEGORIA INTEGER PRIMARY KEY NOT NULL, 
  NM_CATEGORIA TEXT NOT NULL, 
  FL_SEXO TEXT NOT NULL, 
  VL_ANO_INICIAL INTEGER NOT NULL, 
  VL_ANO_FINAL INTEGER NOT NULL, 
  FL_ATIVO TEXT DEFAULT 'S' NOT NULL,
  DT_INCLUSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DT_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TRIGGER tr_categoria_1 AFTER UPDATE ON TB_CATEGORIA
BEGIN
  UPDATE tb_categoria SET dt_alteracao = DATETIME('NOW') WHERE id_categoria = old.id_categoria;
END;

CREATE TABLE TB_EQUIPE (
  ID_EQUIPE INTEGER PRIMARY KEY NOT NULL,
  NM_EQUIPE TEXT NOT NULL,
  FL_ATIVO TEXT DEFAULT 'S' NOT NULL,
  DT_INCLUSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DT_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TRIGGER tr_equipe_1 AFTER UPDATE ON TB_EQUIPE
BEGIN
  UPDATE tb_equipe SET dt_alteracao = DATETIME('NOW') WHERE id_equipe = old.id_equipe;
END;

CREATE TABLE TB_PILOTO (
  ID_PILOTO INTEGER PRIMARY KEY NOT NULL,
  NR_PILOTO INTEGER NOT NULL, 
  NM_PILOTO TEXT NOT NULL, 
  DT_NASCIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ID_CATEGORIA INTEGER NOT NULL CONSTRAINT [FK_CATEGORIA] REFERENCES [TB_CATEGORIA]([ID_CATEGORIA]) ON DELETE CASCADE ON UPDATE CASCADE, 
  ID_EQUIPE INTEGER NOT NULL CONSTRAINT [FK_EQUIPE] REFERENCES [TB_EQUIPE]([ID_EQUIPE]) ON DELETE CASCADE ON UPDATE CASCADE, 
  NM_FOTO BLOB,
  FL_ATIVO TEXT DEFAULT 'S' NOT NULL,
  DT_INCLUSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DT_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TRIGGER tr_piloto_1 AFTER UPDATE ON TB_PILOTO
BEGIN
  UPDATE tb_piloto SET dt_alteracao = DATETIME('NOW') WHERE id_piloto = old.id_piloto;
END;

CREATE TABLE TB_EVENTO (
  ID_EVENTO INTEGER PRIMARY KEY NOT NULL,
  NM_EVENTO TEXT NOT NULL,
  DT_EVENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  NM_OBSERVACAO TEXT,
  FL_ATIVO TEXT DEFAULT 'S' NOT NULL,
  DT_INCLUSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DT_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TRIGGER tr_evento_1 AFTER UPDATE ON TB_EVENTO
BEGIN
  UPDATE tb_evento SET dt_alteracao = current_timestamp WHERE id_evento = old.id_evento;
END;

CREATE TABLE TB_TEMPO (
  ID_TEMPO INTEGER PRIMARY KEY NOT NULL,
  DT_TEMPO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ID_EVENTO INTEGER NOT NULL CONSTRAINT [FK_EVENTO] REFERENCES [TB_EVENTO]([ID_EVENTO]) ON DELETE CASCADE ON UPDATE CASCADE, 
  ID_TOMADA INTEGER NOT NULL CONSTRAINT [FK_TOMADA] REFERENCES [TB_TOMADA]([ID_TOMADA]) ON DELETE CASCADE ON UPDATE CASCADE,
  VL_INTERVALO INTEGER DEFAULT 30 NOT NULL, 
  NM_OBSERVACAO TEXT NOT NULL,
  FL_ATIVO TEXT DEFAULT 'S' NOT NULL,
  DT_INCLUSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DT_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TRIGGER tr_tempo_1 AFTER UPDATE ON TB_TEMPO
BEGIN
  UPDATE tb_tempo SET dt_alteracao = current_timestamp WHERE id_tempo = old.id_tempo;
END;

CREATE TABLE TB_TEMPO_PILOTO (
  ID_TEMPO INTEGER NOT NULL,
  ID_SEQ INTEGER NOT NULL,
  ID_PILOTO INTEGER NOT NULL CONSTRAINT [FK_PILOTO] REFERENCES [TB_PILOTO]([ID_PILOTO]) ON DELETE CASCADE ON UPDATE CASCADE,      
  VL_TEMPO TEXT,
  FL_ATIVO TEXT DEFAULT 'S' NOT NULL,
  DT_INCLUSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  DT_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (ID_TEMPO,ID_SEQ));

CREATE TRIGGER tr_tempo_piloto_1 AFTER UPDATE ON TB_TEMPO_PILOTO
BEGIN
  UPDATE tb_tempo_piloto SET dt_alteracao = current_timestamp WHERE id_tempo = old.id_tempo and id_seq = old.id_seq;
END;






